on:
    push:
        branches:
            - main
jobs:
    Build:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: 🏗 Setup Node
          uses: actions/setup-node@v3
          with:
              node-version: 16.x
        - name: 🏗 Setup Expo
          uses: expo/expo-github-action@v7
          with:
              expo-version: latest
