on:
    workflow_dispatch:
jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: ./.github/workflows/build.yml
            - run: echo "Hello"
